export const languages = [
  { value: "ru", label: "Русский" },
  { value: "en-US", label: "Английский (США)" },
  { value: "en-GB", label: "Английский (Великобритания)" },
  { value: "de", label: "Немецкий" },
  { value: "fr", label: "Французский" },
  { value: "es", label: "Испанский" },
  { value: "it", label: "Итальянский" },
  { value: "pt-PT", label: "Португальский (Португалия)" },
  { value: "pt-BR", label: "Португальский (Бразилия)" },
  { value: "nl", label: "Нидерландский" },
  { value: "sv", label: "Шведский" },
  { value: "da", label: "Датский" },
  { value: "fi", label: "Финский" },
  { value: "pl", label: "Польский" },
  { value: "cs", label: "Чешский" },
  { value: "hu", label: "Венгерский" },
  { value: "el", label: "Греческий" },
  { value: "ro", label: "Румынский" },
  { value: "bg", label: "Болгарский" },
  { value: "sk", label: "Словацкий" },
  { value: "sl", label: "Словенский" },
  { value: "lt", label: "Литовский" },
  { value: "lv", label: "Латышский" },
  { value: "et", label: "Эстонский" },
  { value: "ja", label: "Японский" },
  { value: "zh", label: "Китайский (упрощённый)" },
];

export const categories = [
  { value: "gambling", label: "Гемблинг" },
  { value: "sports_betting", label: "Ставки на спорт" },
  { value: "casino", label: "Казино" },
  { value: "poker", label: "Покер" },
  { value: "lottery", label: "Лотерея" },
  { value: "financial_betting", label: "Финансовые ставки" },
  { value: "esports", label: "Киберспорт" },
  { value: "slots", label: "Слоты" },
  { value: "blackjack", label: "Блэкджек" },
  { value: "roulette", label: "Рулетка" },
  { value: "bingo", label: "Бинго" },
  { value: "live_casino", label: "Живое казино" },
  { value: "fantasy_sports", label: "Фэнтези-спорт" },
  { value: "arcade_games", label: "Аркадные игры" },
];
